version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - npm update -g npm
      - npm install -g grunt-cli
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm install
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - npm run generate
  post_build:
    commands:
      - echo Entered the post_build phase...
      - aws s3 sync --delete dist "s3://docs.starpeace.io/"
      - aws cloudfront create-invalidation --distribution-id EQJ5OVV1B1Y4T --paths / /index.html
      - echo Build completed on `date`

artifacts:
  files:
    - dist/**/*
